import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';

test('advanced action shell is manage-only and requires a selection', async () => {
  const app = await readFile(new URL('../resources/js/components/SmartBrowserApp.vue', import.meta.url), 'utf8');
  const actions = await readFile(new URL('../resources/js/components/ResourceActions.vue', import.meta.url), 'utf8');
  const dialog = await readFile(new URL('../resources/js/components/ResourceBatchDialog.vue', import.meta.url), 'utf8');
  const modeToggle = await readFile(new URL('../resources/js/components/ResourceBatchModeToggle.vue', import.meta.url), 'utf8');
  const fancySelect = await readFile(new URL('../resources/js/components/ResourceFancySelect.vue', import.meta.url), 'utf8');
  const articleAdapter = await readFile(new URL('../package/component/admin/src/Adapter/ArticleCollectionAdapter.php', import.meta.url), 'utf8');
  const categoryAdapter = await readFile(new URL('../package/component/admin/src/Adapter/CategoryAdapter.php', import.meta.url), 'utf8');
  const menuAdapter = await readFile(new URL('../package/component/admin/src/Adapter/MenuAdapter.php', import.meta.url), 'utf8');
  const contentAdapter = await readFile(new URL('../package/component/admin/src/Adapter/ContentAdapter.php', import.meta.url), 'utf8');
  const greek = await readFile(new URL('../package/component/admin/language/el-GR/com_smartbrowser.ini', import.meta.url), 'utf8');

  assert.match(app, /:batch-available="options\.mode === 'manage'"/);
  assert.match(actions, /class="btn btn-outline-secondary resource-batch-toggle"[^>]*:disabled="!selection\?\.length"/);
  assert.match(actions, /fas fa-magic/);
  const css = await readFile(new URL('../package/component/media/css/smartbrowser.css', import.meta.url), 'utf8');
  assert.match(css, /\.resource-action-menu-wrap \{[^}]*margin-inline-start: 12px;/);
  assert.doesNotMatch(css, /\.resource-actions \.resource-batch-toggle \{[^}]*margin-inline-start:/);
  assert.match(css, /\.resource-actions \.btn\.btn-outline-secondary:not\(:disabled\) \{[^}]*color: #41576f !important;[^}]*background: color-mix\(in srgb, var\(--body-bg, #fff\) 72%, var\(--sb-sidebar\)\);/);
  assert.match(css, /\.resource-actions \.btn\.btn-outline-secondary:not\(:disabled\):focus-visible \{[^}]*color: #fff !important;/);
  assert.match(css, /\.btn-outline-secondary:not\(:disabled\) > :is\([^)]*\.fas\) \{\s*color: #2f6fb3;/);
  assert.match(css, /\.resource-filter-buttons \.resource-filter-clear \{[^}]*background: #405b78;/);
  assert.match(css, /\.resource-filter-clear:not\(:disabled\):is\(:hover, :focus-visible\) \{[^}]*background: #6f819a;/);
  assert.match(app, /:adapter="options\.adapter" :filters="state\.presentation\.filters"/);
  assert.match(dialog, /items\.length/);
  assert.match(dialog, /class="resource-batch-heading"/);
  assert.match(dialog, /class="resource-batch-heading" role="heading" aria-level="3"/);
  assert.match(dialog, /class="resource-batch-preview-heading" role="heading" aria-level="3"/);
  assert.match(dialog, /class="resource-batch-summary-step-heading" role="heading" aria-level="4"/);
  assert.doesNotMatch(dialog, /<h[1-6]\b/);
  assert.doesNotMatch(dialog, /class="resource-batch-count"/);
  assert.match(dialog, /v-if="isMedia"/);
  assert.match(dialog, /v-else-if="isArticles"/);
  assert.match(dialog, /<details class="resource-batch-step" :open="media\.rename"/);
  assert.match(dialog, /v-model="media\.placement"/);
  assert.match(dialog, /<ResourceBatchModeToggle v-model="media\.placement"/);
  assert.match(dialog, /<details class="resource-batch-step" :open="media\.zip"/);
  assert.match(dialog, /:open="article\[field\.enabled\]"/);
  assert.doesNotMatch(dialog, /<summary[^>]*><b>/);
  assert.match(dialog, /filterOptions\(field\.id\)/);
  assert.match(dialog, /v-model="article\.placement"/);
  assert.match(dialog, /<ResourceBatchModeToggle v-model="article\.placement"/);
  assert.equal((dialog.match(/<ResourceBatchModeToggle/g) || []).length, 4);
  assert.match(modeToggle, /class="btn-group resource-batch-mode-toggle" role="group"/);
  assert.match(modeToggle, /:aria-pressed="modelValue === mode\.value"/);
  assert.match(dialog, /:model-value="article\.tagAdd"[^>]* multiple /);
  assert.match(dialog, /:model-value="article\.tagRemove"[^>]* multiple /);
  assert.match(dialog, /<ResourceFancySelect v-model="article\.category"/);
  assert.match(dialog, /props\.batchOptions\[id\]/);
  assert.match(fancySelect, /<joomla-field-fancy-select/);
  assert.match(fancySelect, /choicesInstance/);
  assert.match(fancySelect, /'resource-batch-single-select': !multiple/);
  assert.match(articleAdapter, /'category' => \$this->categoryOptions\(true\)/);
  assert.match(articleAdapter, /'tag' => \$this->batchTagOptions\(\)/);
  assert.match(contentAdapter, /HTMLHelper::_\('tag\.tags', \['filter\.published' => \[1\]\]\)/);
  assert.match(categoryAdapter, /'category' => array_merge\(\[\['value' => '1'/);
  assert.match(categoryAdapter, /'tag' => \$this->batchTagOptions\(\)/);
  assert.match(menuAdapter, /'menuParent' => array_values\(array_map/);
  assert.match(dialog, /v-else-if="isCategories \|\| isTags \|\| isMenus"/);
  assert.match(dialog, /v-else-if="isUsers"/);
  assert.match(dialog, /shared\.flipOrdering/);
  assert.match(dialog, /menuDestinationOptions/);
  assert.match(dialog, /user\.groupAction/);
  assert.match(dialog, /user\.resetOpen/);
  assert.match(dialog, /v-if="step\.parameters\.length \|\| step\.preview"/);
  assert.match(contentAdapter, /\$batchDestination && !in_array\(\(int\) \$category->published, \[0, 1\], true\)/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_SET_LANGUAGE="Αλλαγή γλώσσας"/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_SET_ACCESS="Αλλαγή πρόσβασης"/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_TAGS="Αλλαγή ετικετών"/);
  assert.match(dialog, /ref="previewDialog"/);
  assert.match(dialog, /@click="openPreview"/);
  assert.match(dialog, /ref="selectionDialog"/);
  assert.match(dialog, /@click="openSelection"/);
  assert.match(dialog, /items\.length === 1 \? 'COM_SMARTBROWSER_SELECTED_ITEM_COUNT_ONE' : 'COM_SMARTBROWSER_SELECTED_ITEM_COUNT_MANY'/);
  assert.match(dialog, /<strong>\{\{ t\('COM_SMARTBROWSER_SELECTED_ITEMS'\) \}\}<\/strong>/);
  assert.match(dialog, /:class="item\.icon \|\| 'fas fa-file'"/);
  assert.match(css, /\.resource-batch-selected-list \{[^}]*list-style: none;/);
  assert.match(dialog, /class="resource-batch-sequence-item"/);
  assert.match(dialog, /v-if="index" class="fas fa-arrow-right resource-batch-sequence-arrow"/);
  assert.match(dialog, /parameters: article\.tagAdd\.map/);
  assert.match(css, /\.resource-batch-summary \{ display: flex; flex-wrap: wrap;/);
  assert.match(css, /\.resource-batch-heading \{[^}]*padding-bottom: 3px;[^}]*border-bottom: 2px solid #aebdcc; font-size: 1\.083rem;/);
  assert.match(css, /\.resource-batch-preview-heading \{[^}]*padding-bottom: 3px;[^}]*border-bottom: 2px solid #aebdcc; font-size: 1\.083rem;/);
  assert.match(css, /\.resource-batch-body \{ flex: 1 1 auto; min-height: 0; overflow: auto;/);
  assert.match(css, /\.resource-batch-bottom \{ flex: none; border-top: 1px solid var\(--sb-border\); \}/);
  assert.match(css, /\.resource-batch-sequence-item \{ display: flex;/);
  assert.match(css, /\.resource-batch-fields \.resource-batch-mode-select \{ min-height: 44px; \}/);
  assert.match(css, /\.resource-batch-mode-toggle \{ display: flex; height: 44px;/);
  assert.match(css, /\.resource-batch-mode-toggle \.btn\.is-active \{[^}]*background: #277a53;/);
  assert.match(dialog, /<div class="resource-batch-bottom">\s*<div class="resource-batch-preview">/);
  assert.match(css, /\.resource-batch-choices-dropdown:popover-open \{[^}]*overflow: hidden;/);
  assert.match(css, /\.resource-batch-choices-dropdown:popover-open \.choices__list \{ max-height: min\(300px, var\(--resource-batch-dropdown-list-height, 300px\)\);/);
  assert.match(fancySelect, /const openAbove = below < 240 && above > below;/);
  assert.doesNotMatch(dialog, /resource-batch-header/);
  assert.match(dialog, /SmartBrowserDialogDismiss\.install\(dialog\.value, \(\) => dirty\.value\)/);
  assert.match(dialog, /COM_SMARTBROWSER_BATCH_APPLY/);
  assert.match(dialog, /class="btn btn-primary" :disabled="busy \|\| !canApply" @click="apply"/);
  assert.match(css, /\.resource-batch-step summary \{[^}]*color: #fff; background: #444b53;[^}]*border-inline-start: 3px solid #30363c;/);
  assert.match(css, /\.resource-batch-step\[open\] summary \{[^}]*color: #fff; background: #277a53;[^}]*font-weight: 600;/);
  assert.match(css, /\.resource-batch-step\[open\] summary::after \{[^}]*border-color: #fff;/);
  assert.match(css, /\.resource-batch-step\[open\]:focus-within \{ z-index: 3; \}/);
  assert.match(css, /\.resource-batch-fields \.resource-batch-field:focus-within \{ position: relative; z-index: 2; \}/);
  assert.match(css, /\.resource-batch-single-select \.choices__button_joomla \{ display: none; \}/);
  assert.match(css, /\.com-smartbrowser-editor \.choices\[data-type\*="select-multiple"\] \.choices__button_joomla \{[^}]*text-indent: -9999px;/);
  assert.match(css, /\.com-smartbrowser-editor \.choices\[data-type\*="select-multiple"\] \.choices__button_joomla:focus-visible \{ outline: 2px solid #fff;/);
  assert.match(css, /\.com-smartbrowser-editor \.choices\[data-type\*="select-multiple"\] \.choices__list--multiple \.choices__item \{ margin: 0 4px 3px 0; padding: 2px 7px;/);
  assert.doesNotMatch(css, /\.com-smartbrowser-editor \.smartbrowser-editor-tab \.choices__button_joomla \{/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_ADD_TAG="Προσθήκη ετικετών"/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_REMOVE_TAG="Αφαίρεση ετικετών"/);
  assert.match(fancySelect, /dropdown\.showPopover\(\)/);
  assert.match(fancySelect, /parentDialog\?\.addEventListener\('close', closeDropdown\)/);
  assert.match(css, /\.resource-batch-choices-dropdown:popover-open \{ position: fixed !important;/);
  assert.match(greek, /COM_SMARTBROWSER_BATCH_PREVIEW="Σύνοψη"/);
});
