async page => {
  const check = (value, message) => { if (!value) throw new Error(message); };
  page.setDefaultTimeout(10000);
  await page.goto('http://127.0.0.1:8791');
  await page.setViewportSize({ width: 1280, height: 900 });
  const frame = () => page.frameLocator('dialog.smartbrowser-picker iframe');
  const select = () => frame().locator('.resource-actions').getByRole('button', { name: 'Select', exact: true }).click();
  const closed = () => page.locator('dialog.smartbrowser-picker').waitFor({ state: 'detached' });
  const result = async () => JSON.parse(await page.locator('#result').innerText());
  await page.evaluate(() => sessionStorage.setItem('supjx.smartbrowser.media', JSON.stringify({ showInfo: false, activeView: 'grid' })));
  await page.locator('#images').click();
  await frame().locator('.resource-usage-editor').waitFor();
  check(await frame().getByRole('tab', { name: 'Usage options' }).getAttribute('aria-selected') === 'true', 'Usage must be initially active');
  check(await frame().locator('.resource-usage-secondary').getAttribute('open') === null, 'Secondary options must be collapsed');
  await select();
  await frame().getByText('A value is required.', { exact: true }).waitFor();
  await frame().locator('.resource-usage-field input[type=text]').fill('Description');
  await frame().locator('.resource-usage-secondary summary').click();
  await frame().locator('.resource-usage-field select').selectOption('lazy');
  await select(); await closed();
  check((await result()).usage['local-images:/a.png']['media.loading'] === 'lazy', 'Usage values were not returned');
  await page.locator('#legacy').click();
  await frame().locator('.resource-browser-grid').waitFor();
  check(await frame().locator('.resource-info-panel').count() === 0, 'Forced Info open must not leak to the next picker');
  check(JSON.parse(await page.evaluate(() => sessionStorage.getItem('supjx.smartbrowser.media'))).showInfo === false, 'Remembered preference changed');
  await page.locator('dialog.smartbrowser-picker > .btn-close').click();
  await page.locator('#pdf').click();
  await frame().locator('.resource-usage-reference > span').filter({ hasText: 'Second image' }).waitFor();
  await frame().getByRole('button', { name: 'Choose image', exact: true }).click();
  const nested = frame().frameLocator('dialog.smartbrowser-picker iframe');
  await nested.locator('.resource-browser-item').first().waitFor();
  check(await nested.locator('.resource-browser-item').filter({ hasText: 'Report PDF' }).getAttribute('aria-pressed') === null, 'Nested picker allowed non-images');
  await nested.locator('.resource-item-title').getByText('First image', { exact: true }).dblclick();
  await frame().locator('dialog.smartbrowser-picker').waitFor({ state: 'detached' });
  await frame().locator('.resource-usage-reference > span').filter({ hasText: 'First image' }).waitFor();
  check(await page.locator('dialog.smartbrowser-picker').count() === 1, 'Nested selection closed the outer picker');
  await select(); await closed();
  check((await result()).usage['local-images:/report.pdf']['media.thumbnailOverride'].id === 'local-images:/a.png', 'Thumbnail reference was not updated');
  await page.locator('#pdf').click();
  await frame().locator('.resource-usage-reference > span').waitFor();
  await frame().locator('.resource-usage-field > select').selectOption('auto');
  await select(); await closed();
  check((await result()).usage['local-images:/report.pdf']['media.thumbnailOverride'] === null, 'Thumbnail was not cleared');
  await page.locator('#multiple').click();
  await frame().locator('.resource-usage-editor').waitFor();
  await frame().locator('.resource-usage-field input[type=text]').fill('Second label');
  await frame().locator('.resource-browser-item').filter({ has: frame().locator('.resource-item-title', { hasText: 'First image' }) }).locator('.resource-item-menu-toggle').click();
  await frame().locator('.resource-usage-field input[type=text]').fill('First label');
  await select(); await closed();
  const multi = await result();
  check(multi.selection.map(resource => resource.id).join(',') === 'local-images:/b.png,local-images:/a.png', 'Initial selection order was lost');
  check(multi.usage['local-images:/a.png']['media.alt'] === 'First label' && multi.usage['local-images:/b.png']['media.alt'] === 'Second label', 'Per-resource state leaked');
  await page.locator('#article').click();
  await frame().locator('.resource-usage-field input').waitFor();
  await frame().getByRole('button', { name: 'Preview action', exact: true }).click();
  await frame().locator('.resource-usage-field input').filter({ visible: true }).waitFor();
  check(await frame().locator('.resource-usage-field input').inputValue() === 'From preview', 'Custom editor did not receive preview updates');
  await select(); await closed();
  check((await result()).usage['article:1']['example.label'] === 'From preview', 'Non-media capability did not work');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#images').click();
  await frame().locator('.resource-usage-editor').waitFor();
  const fits = await frame().locator('.resource-usage-field input[type=text]').evaluate(input => input.getBoundingClientRect().right <= window.innerWidth);
  check(fits, 'Usage controls overflow mobile frame');
  await page.screenshot({ path: '.playwright-mcp/picker-usage-mobile.png' });
  await page.locator('dialog.smartbrowser-picker > .btn-close').click();
  return 'Image defaults/validation, Info persistence, nested PDF picker/change/remove, ordered multiple selection, non-media custom editor/preview action and mobile layout OK';
}
